apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M=   # "rootpass"
  mysql-user: dXNlcg==               # "user"
  mysql-password: cGFzc3dvcmQ=       # "password"
  mysql-database: bXlkYg==           # "mydb"

