apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: us.icr.io/khalidalinginx/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-storage
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-prod-pvc
      imagePullSecrets:
        - name: ibmcr-secret

